# Generated by Django 5.2.3 on 2025-06-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='comapny_address',
            new_name='company_address',
        ),
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.ManyToManyField(blank=True, to='base.department'),
        ),
    ]
